---
name: "Install MacPorts Ports"
inputs:
  ARCH:
    required: true
    type: string
  CROSS_COMPILE:
    required: true
    type: boolean
  PYVERS:
    required: true
    type: string
  PYDOTVERS:
    required: true
    type: string
  DBVERS:
    required: true
    type: string
  COMPILER:
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: "Install X11 dependencies on MacOS"
      id: install_x11
      if: runner.os == 'macOS'
      shell: bash
      run: |
        # install xquartz for the targeted environment
        # this must be done before we remove homebrew
        if $CROSS_COMPILE; then
          arch -${ARCH} brew install --cask xquartz
        else
          brew install --cask xquartz
        fi
    - name: "Bootstrap MacPorts"
      id: install_macports
      shell: bash
      env:
        GH_URL: "https://raw.githubusercontent.com"
        MP_URL: "GiovanniBussi/macports-ci/master/macports-ci"
      run: |
        if hash port 2>/dev/null; then
          echo "Macports is already installed"
        else
          curl -LJO "${GH_URL}/${MP_URL}"
          chmod +x macports-ci
          if $CROSS_COMPILE; then
            #install macports for cross-compile arch
            arch -${ARCH} ./macports-ci install
            # running the install with arch doesn't set the current environment, source
            # this needs to be done manually
            # this only will work if macports is installed in the default location
            if [ ! -f ~/.bashrc ]; then
              cp /etc/bashrc ~/.bashrc
            fi
            echo 'export PATH=/opt/local/bin:/opt/local/sbin:$PATH' >> ~/.bashrc
            echo 'export MANPATH=/opt/local/share/man:$MANPATH' >> ~/.bashrc
            echo 'export DISPLAY=:0.0' >> ~/.bashrc
            source ~/.bashrc
          else
            #install macports for system arch
            source ./macports-ci install
          fi
        fi
    - name: "Remove Homebrew"
      id: remove_homebrew
      shell: bash
      env:
        GH_URL: "https://raw.githubusercontent.com"
        HB_URL: "Homebrew/install/HEAD/uninstall.sh"
      run: |
        if hash brew 2>/dev/null; then
          # now remove homebrew to prevent python conflicts
          /bin/bash -c "$(curl -fsSL ${GH_URL}/${HB_URL})" --force
          sudo rm -Rf /usr/local/bin/brew
        fi
    - name: "Setup Macports Environment"
      id: mp_env
      shell: bash
      run: |
        PKGMGR_CMD=$(which port)
        PKGMGR_PATH=$(dirname $(dirname $PKGMGR_CMD))
        # If we're cross-compiling, we need to change this to the selected arch
        if $CROSS_COMPILE; then
          PKGMGR_CMD="sudo arch -${ARCH} $PKGMGR_CMD"
        else
          PKGMGR_CMD="sudo $PKGMGR_CMD"
        fi
        echo "PKGMGR_CMD=$PKGMGR_CMD" >> $GITHUB_ENV
        echo "PKGMGR_PATH=$PKGMGR_PATH" >> $GITHUB_ENV
        echo "PKGMGR_BIN=$PKGMGR_PATH/bin" >> $GITHUB_ENV
        export PATH=$PATH:$PKGMGR_BIN
    - name: "Install required support ports"
      id: install_req_ports
      shell: bash
      env:
        PYVERS: ${{ inputs.PYVERS }}
        COMPILER: ${{ inputs.COMPILER }}
      run: |
        ${PKGMGR_CMD} -N install gsed \
          ccache \
          py${PYVERS}-ansible \
          py${PYVERS}-virtualenv \
          py${PYVERS}-pkgconfig \
          py${PYVERS}-setuptools \
          py${PYVERS}-pip \
          ${DBVERS}
        ${PKGMGR_CMD} select --set python python${PYVERS}
        ${PKGMGR_CMD} select --set python3 python${PYVERS}
        ${PKGMGR_CMD} select --set pip pip${PYVERS}
        ${PKGMGR_CMD} select --set pip3 pip${PYVERS}
        ${PKGMGR_CMD} select --set ansible py${PYVERS}-ansible
        ${PKGMGR_CMD} select --set virtualenv virtualenv${PYVERS}
        if [ $COMPILER != "clang" ];then
          CLANG_PORT=${COMPILER//clang-mp/clang}
          ${PKGMGR_CMD} install $CLANG_PORT
        fi
        ANS_PB=${PKGMGR_BIN}/ansible-playbook-${PYDOTVERS}
        if $CROSS_COMPILE; then
          ANS_PB="arch -${ARCH} $ANS_PB"
        fi
        echo "ANS_PB=$ANS_PB" >> $GITHUB_ENV
    - name: "Install required ports via ansible"
      id: ansible_install
      shell: bash
      env:
        PYDOTVERS: ${{ inputs.PYDOTVERS }}
        DBVERS: ${{ inputs.DBVERS }}
      run: |
        echo "Cloninng MythTV anible repo"
        git clone https://github.com/MythTV/ansible.git
        cd ansible
        echo "Installing ports via ansible playbook"
        export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$PKGMGR_PATH/lib/mysql8/pkgconfig/
        export MYSQLCLIENT_LDFLAGS=$(pkg-config --libs mysqlclient)
        export MYSQLCLIENT_CFLAGS=$(pkg-config --cflags mysqlclient)
        XTRA_VARS="ansible_python_interpreter=${PKGMGR_BIN}/python${PYDOTVERS} \
          database_version=${DBVERS} \
          install_qtwebkit=true"
        ${ANS_PB} mythtv.yml --extra-vars="$XTRA_VARS" --limit=localhost
    - name: "Cleanup maports install"
      id: port_cleanup
      shell: bash
      run: |
        echo "Cleaning up macports builds"
        # force ownership for the users ansible / mythtv temp directories
        sudo chown $(id -u):$(id -g) ~/.ansible
        sudo chown $(id -u):$(id -g) ~/.mythtv
        sudo rm -rf ${PKGMGR_PATH}/var/macports/build/*
        sudo rm -rf ${PKGMGR_PATH}/var/macports/distfiles/*
