---
name: "Reusable WF: Build Sign and Upload Mythfrontend"

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      MYTHBRANCH:
        required: true
        type: string
        default: master
      USE_CCACHE:
        required: true
        type: boolean
        default: false
      PKGMGR:
        required: true
        type: string
        default: macports
jobs:
  build:
    name: Building MythTV on ${{ matrix.os.desc }} using ${{ matrix.compiler.desc }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - desc: 'macOS 13 (Ventura) x86_64'
            runner: 'macOS-13'
            arch: 'x86_64'
            cross_compile: false
          - desc: 'macOS 14 (Sonoma) arm64'
            runner: 'macOS-14'
            arch: 'arm64'
            cross_compile: false
          - desc: 'macOS 15 (Sequoia) arm64'
            runner: 'macOS-15'
            arch: 'arm64'
            cross_compile: false
        build_homebrew:
          - ${{ inputs.PKGMGR == 'homebrew' }}
    runs-on: ${{ matrix.os.runner }}
    env:
      COMPILER: "clang"
      APP_OUT_DIR: "output_dir"
      MASTER_VERS: 35
      ARCH: ${{ matrix.os.arch }}
      MYTHBRANCH: ${{ inputs.MYTHBRANCH }}
      USE_CCACHE: ${{ inputs.USE_CCACHE }}
      PKGMGR: ${{ inputs.PKGMGR }}
    steps:
      - uses: actions/checkout@master
      - name: "Setup environemental variables"
        run: |
          APP_OUT_DIR=$HOME/$APP_OUT_DIR
          case $PKGMGR in
            macports)
              PYVERS="311"
              PYDOTVERS="3.11"
              DBVERS="mysql8"
              QTVERS="qt5"
              echo "USE_MP=true" >> $GITHUB_ENV
              echo "USE_HB=false" >> $GITHUB_ENV
            ;;
            homebrew)
              PYVERS="313"
              PYDOTVERS="3.13"
              ANSIBLEVERS="10"
              DBVERS="mysql"
              QTVERS="qt@5"
              echo "ANSIBLEVERS=$ANSIBLEVERS" >> $GITHUB_ENV
              echo "USE_MP=false" >> $GITHUB_ENV
              echo "USE_HB=true" >> $GITHUB_ENV
            ;;
          esac
          echo "PYVERS=${PYVERS}" >> $GITHUB_ENV
          echo "PYDOTVERS=${PYDOTVERS}" >> $GITHUB_ENV
          echo "DBVERS=${DBVERS}" >> $GITHUB_ENV
          echo "QTVERS=${QTVERS}" >> $GITHUB_ENV
          BLD_FLGS="--repo-prefix=${GITHUB_WORKSPACE} \
            --version=${MYTHBRANCH} \
            --python-version=${PYVERS} \
            --database-version=${DBVERS} \
            --qt-version=${QTVERS} \
            --alt-compiler=${COMPILER} \
            --skip-ansible=true \
            --update-git=false"
          #check if this is a cross compile
          SYSARCH=$(/usr/bin/uname -m)
          case $MYTHBRANCH in
            *fixes*)
              VERSNUM=${MYTHBRANCH#*/}
            ;;
            *master*)
              VERSNUM=${MASTER_VERS}
            ;;
            *)
              echo "Bad MYTHVERS"
              exit 1
            ;;
          esac
          echo "APP_OUT_DIR=${APP_OUT_DIR}" >> $GITHUB_ENV
          EXE="mythfrontend.app"
          echo "APP_W=${APP_OUT_DIR}/with_plugins/$EXE" >> $GITHUB_ENV
          echo "APP_WO=${APP_OUT_DIR}/without_plugins/$EXE" >> $GITHUB_ENV
          echo "BLD_FLGS=${BLD_FLGS}" >> $GITHUB_ENV
          echo "SYSARCH=$SYSARCH" >> $GITHUB_ENV
          echo "OS_VERS=$(sw_vers -productVersion | awk -F '.' '{print $1}')" >> $GITHUB_ENV
          echo "VERSNUM=$VERSNUM" >> $GITHUB_ENV
      - name: "Checkout MythTV/ansible repository"
        uses: actions/checkout@v4
        with:
          repository: MythTV/ansible
          path: ansible
      - name: "Install MacPorts Ports"
        if: ${{ env.USE_MP == 'true' }}
        uses: ./.github/actions/installPorts
        id: installMP
        with:
          ARCH: ${{ matrix.os.arch }}
          CROSS_COMPILE: ${{ matrix.os.cross_compile }}
          PYVERS: ${{ env.PYVERS }}
          PYDOTVERS: ${{ env.PYDOTVERS }}
          DBVERS: ${{ env.DBVERS }}
          QTVERS: ${{env.QTVERS}}
          COMPILER: ${{ env.COMPILER }}
      - name: "Install Homebrew Packages"
        if: ${{ env.USE_HB == 'true' }}
        uses: ./.github/actions/installBrewPackages
        id: installHB
        with:
          ARCH: ${{ matrix.os.arch }}
          CROSS_COMPILE: ${{ matrix.os.cross_compile }}
          PYVERS: ${{ env.PYVERS }}
          PYDOTVERS: ${{ env.PYDOTVERS }}
          ANSIBLEVERS: ${{ env.ANSIBLEVERS }}
          DBVERS: ${{ env.DBVERS }}
          QTVERS: ${{env.QTVERS}}
          COMPILER: ${{ env.COMPILER }}
      - name: Checkout Mythtv/mythtv repository
        uses: actions/checkout@v4
        with:
          repository: MythTV/mythtv
          ref: ${{ env.MYTHBRANCH }}
          path: "mythtv-${{ env.VERSNUM }}/mythtv"
      - name: "Compile MythTV"
        uses: ./.github/actions/compile
        id: compile
        with:
          APP_OUT_DIR: ${{ env.APP_OUT_DIR }}
          APP_W: ${{ env.APP_W }}
          APP_WO: ${{ env.APP_WO }}
          OS: ${{ matrix.os.runner }}
          ARCH: ${{ matrix.os.arch }}
          CROSS_COMPILE: ${{ matrix.os.cross_compile }}
          BLD_FLGS: ${{ env.BLD_FLGS }}
          VERSNUM: ${{ env.VERSNUM }}
          USE_CCACHE: ${{ env.USE_CCACHE }}
      - name: "Test Mythfrontend"
        id: test_app
        shell: bash
        env:
          ARCH: ${{ matrix.os.arch }}
        run: |
          echo "Testing mythfrontend.app"
          EXE="$APP_W/Contents/MacOS/mythfrontend --version"
          if ${CROSS_COMPILE}; then
            EXE="arch -${ARCH} $EXE"
          fi
          VERSTR=$($EXE |grep "MythTV Version"|gsed "s/^.*Version : *//")
          echo "Extracted Version String: $VERSTR"
          echo "Creating output DMG names"
          DMG_W="MythFrontend-${ARCH}-$OS_VERS-macOS$VERSTR-with-plugins.dmg"
          DMG_WO="MythFrontend-${ARCH}-$OS_VERS-macOS$VERSTR.dmg"
          echo "DMG_W=$DMG_W" >> $GITHUB_ENV
          echo "DMG_WO=$DMG_WO" >> $GITHUB_ENV
      - name: "Codesign Mythfrontend"
        uses: ./.github/actions/codesign
        id: codesign
        with:
          APP_OUT_DIR: ${{ env.APP_OUT_DIR }}
          APP_W: ${{ env.APP_W }}
          APP_WO: ${{ env.APP_WO }}
          DMG_W: ${{ env.DMG_W }}
          DMG_WO: ${{ env.DMG_WO }}
          CERT: ${{ secrets.PROD_MACOS_CERTIFICATE }}
          CERT_PWD: ${{ secrets.PROD_MACOS_CERTIFICATE_PWD }}
          CERT_NAME: ${{ secrets.PROD_MACOS_CERTIFICATE_NAME }}
          CI_PWD: ${{ secrets.PROD_MACOS_CI_KEYCHAIN_PWD }}
          APPLE_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_APPLE_ID }}
          TEAM_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_TEAM_ID }}
          NOTA_PWD: ${{ secrets.PROD_MACOS_NOTARIZATION_PWD }}
      - uses: webfactory/ssh-agent@master
        with:
          ssh-private-key: ${{ secrets.SF_PRIV_KEY }}
      - name: "Upload to SourceForge"
        uses: ./.github/actions/upload
        id: upload
        with:
          DMG_W: ${{ env.DMG_W }}
          DMG_WO: ${{ env.DMG_WO }}
          VERSNUM: ${{ env.VERSNUM }}
          OS_VERS: ${{ env.OS_VERS }}
          ARCH: ${{ matrix.os.arch }}
          PKGMGR: ${{ env.PKGMGR }}
          SF_LOGIN: ${{ secrets.SF_LOGIN }}
