---
name: "Manual build"

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      mythbranch:
        type: choice
        description: "Choose a MythTV Version"
        options:
          - "master"
          - "fixes/33"
          - "fixes/32"
      BUILD_x86_64:
        type: boolean
        description: "Build x86_64"
      BUILD_ARM64:
        type: boolean
        description: "Build ARM64"

run-name: "Manual Build: ${{ inputs.mythbranch }} by @${{ github.actor }}"

jobs:
  check-inputs:
    runs-on: 'macos-latest'
    env:
      mythbranch: ${{ inputs.mythbranch }}
      BUILD_x86_64: ${{ inputs.BUILD_x86_64 }}
      BUILD_ARM64: ${{ inputs.BUILD_ARM64 }}
    steps:
      - name:
        run: |
          outputSTR="Building MyhtvTV Branch $mythbranch for"
          if [ $BUILD_x86_64 ]; then
            outputSTR="$outputSTR x86_64"
          fi
          if [ $BUILD_ARM64 ]; then
            outputSTR="$outputSTR ARM64"
          fi
          echo $outputSTR
  build-mythtv-x86_64:
    needs: check-inputs
    if: ${{ github.event.inputs.BUILD_x86_64 == 'true' }}
    uses: ./.github/workflows/build_sign_upload.yml
    with:
      BUILD_x86_64: true
      BUILD_ARM64: false
      USE_CCACHE: false
      MYTHBRANCH: ${{ inputs.mythbranch }}
    secrets: inherit
  build-mythtv-arm64:
    needs: check-inputs
    if: ${{ github.event.inputs.BUILD_ARM64 == 'true' }}
    uses: ./.github/workflows/build_sign_upload.yml
    with:
      BUILD_x86_64: false
      BUILD_ARM64: true
      USE_CCACHE: false
      MYTHBRANCH: ${{ inputs.mythbranch }}
    secrets: inherit
