name: "Manual build"

on:
  workflow_dispatch:
    inputs:
      mythbranch:
        type: choice
        description: "Choose a MythTV Version"
        options:
        - "master"
        - "fixes/33"
        - "fixes/32"
      debug:
        type: boolean
        description: "Debug Build"

run-name: "Manual Build: ${{ inputs.mythbranch }} - Debug=${{ inputs.debug }} by @${{ github.actor }}"

jobs:
  build-mythtv-fixes:
    uses: ./.github/workflows/build.yml
    with:
      MYTHBRANCH: ${{ inputs.mythbranch }}
      DEBUGBUILD: ${{ inputs.debug }}
    secrets: inherit