name: "Manual debug build (master)"

on: [workflow_dispatch]

jobs:
  build-mythtv-master:
    uses: ./.github/workflows/build.yml
    with:
      MYTHBRANCH: "master"
      VERSNUM: 34
      DEBUGBUILD: true
    secrets: inherit
