name: "Manual build (Original)"

on:
  workflow_dispatch:
    inputs:
      mythbranch:
        type: choice
        description: "Choose a MythTV Version"
        options:
          - "master"
          - "fixes/33"
          - "fixes/32"
      build_intel:
        type: boolean
        description: "Build Intel"
      build_arm64:
        type: boolean
        description: "Build Arm64"
      debug:
        type: boolean
        description: "Debug Build"

run-name: "Manual Build (Orig): ${{ inputs.mythbranch }} - Debug=${{ inputs.debug }} by @${{ github.actor }}"

jobs:
  build-mythtv-intel:
    if: ${{ github.event.inputs.build_intel == 'true' }}
    uses: ./.github/workflows/build.yml
    with:
      MYTHBRANCH: ${{ inputs.mythbranch }}
      DEBUGBUILD: ${{ inputs.debug }}
    secrets: inherit
  build-mythtv-arm64:
    if: ${{ github.event.inputs.build_arm64 == 'true' }}
    uses: ./.github/workflows/build_ARM.yml
    with:
      MYTHBRANCH: ${{ inputs.mythbranch }}
      DEBUGBUILD: ${{ inputs.debug }}
    secrets: inherit
