---
name: "Manual build"

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      MYTHBRANCH:
        type: choice
        description: "Choose a MythTV Version"
        options:
          - "master"
          - "fixes/34"
          - "fixes/33"
          - "fixes/32"
      PKGMGR:
        type: choice
        description: "Choose a package manager"
        options:
          - "macports"
          - "homebrew"

run-name: "Manual Build: ${{ inputs.mythbranch }} by @${{ github.actor }}
  with ${{ inputs.PKGMGR }}"

jobs:
  check-inputs:
    runs-on: 'macos-latest'
    env:
      mythbranch: ${{ inputs.MYTHBRANCH }}
    steps:
      - name:
        run: |
          outputSTR="Building MyhtvTV Branch $mythbranch"
          echo $outputSTR
  build-mythtv:
    needs: check-inputs
    uses: ./.github/workflows/build_sign_upload.yml
    with:
      USE_CCACHE: false
      MYTHBRANCH: ${{ inputs.MYTHBRANCH }}
      PKGMGR: ${{ inputs.PKGMGR }}
    secrets: inherit
