name: "Manual build (master)"

on: [workflow_dispatch]

jobs:
  build-mythtv-master:
    uses: ./.github/workflows/build.yml
    with:
      MYTHBRANCH: "master"
      VERSNUM: 33
    secrets: inherit
